import {
  LayoutDashboard,
  Users,
  ShieldCheck,
  HeartPulse,
  HardHat,
  ScanLine,
  ClipboardList,
  FileBarChart,
  Settings,
  Eye,
  Bell,
  Building2,
  FileText,
  PlusCircle,
  UserPlus,
  Truck,
  Wrench,
  Inbox,
  Activity,
  Download,
  Stethoscope,
  History,
  Ban,
  ClipboardCheck,
  IdCard,
  Clock,
  Zap,
  Boxes,
  ArrowLeftRight,
  BadgeCheck,
  Megaphone,
} from "lucide-react";

import { ROLE_VALUES, type Role, type RoleConfig } from "@/types";

export const ROLES = [...ROLE_VALUES];

export const roleToDashboard: Record<Role, string> = {
  SUPER_ADMIN: "/super-admin",
  ADMIN_HSEQ: "/admin",
  MEDICAL_OFFICER: "/medical",
  HSEQ_OFFICER: "/hseq",
  SECURITY_OFFICER: "/security",
  INTERNAL_SECURITY: "/internal-security",
  CONTRACTOR: "/contractor",
};

export const roleConfig: Record<Role, RoleConfig> = {
  SUPER_ADMIN: {
    label: "Super Administrator",
    shortLabel: "Super Admin",
    dashboardPath: "/super-admin",
    description: "Full platform oversight, user & role management.",
    nav: [
      { label: "Command Center", href: "/super-admin", icon: LayoutDashboard },
      { label: "User Management", href: "/super-admin/users", icon: Users },
      { label: "All Contractors", href: "/super-admin/contractors", icon: Building2 },
      { label: "All Employees", href: "/super-admin/employees", icon: HardHat },
      { label: "All Vehicles", href: "/super-admin/vehicles", icon: Truck },
      { label: "All Equipment", href: "/super-admin/equipment", icon: Wrench },
      { label: "Permanent Movements", href: "/permanent-movements", icon: BadgeCheck },
      { label: "Reports Center", href: "/super-admin/reports", icon: FileBarChart },
      { label: "Announcements", href: "/super-admin/announcements", icon: Megaphone },
      { label: "Audit Log", href: "/super-admin/audit-log", icon: ClipboardList },
      { label: "Notifications", href: "/notifications", icon: Bell },
      { label: "System Settings", href: "/super-admin/settings", icon: Settings },
    ],
  },
  ADMIN_HSEQ: {
    label: "Administrator — HSEQ",
    shortLabel: "Admin",
    dashboardPath: "/admin",
    description: "Operational administration across HSEQ workflows.",
    nav: [
      { label: "Dashboard", href: "/admin", icon: LayoutDashboard },
      { label: "Contractor Registrations", href: "/admin/registrations", icon: FileText },
      { label: "Additional Requests", href: "/admin/additional-requests", icon: PlusCircle },
      { label: "Create Contractor", href: "/admin/registrations?status=APPROVED", icon: UserPlus },
      { label: "Vehicles", href: "/admin/vehicles", icon: Truck },
      { label: "Tools & Equipment", href: "/admin/tools-inventory", icon: Wrench },
      { label: "Visitor Passes", href: "/admin/visitor-passes", icon: IdCard },
      { label: "Visitor History", href: "/admin/visitor-history", icon: History },
      { label: "Gate Movements", href: "/admin/movements", icon: ArrowLeftRight },
      { label: "Permanent Employees", href: "/admin/permanent-employees", icon: BadgeCheck },
      { label: "Permanent Movements", href: "/permanent-movements", icon: ArrowLeftRight },
      { label: "Employee QR Codes", href: "/admin/employee-qr-codes", icon: Download },
      { label: "Expired ID Cards", href: "/admin/expired-ids", icon: Clock },
      { label: "Reports", href: "/admin/reports", icon: FileBarChart },
      { label: "Notifications", href: "/notifications", icon: Bell },
    ],
  },
  MEDICAL_OFFICER: {
    label: "Medical Officer",
    shortLabel: "Medical",
    dashboardPath: "/medical",
    description: "Medical fitness clearance and NIC blacklisting.",
    nav: [
      { label: "Dashboard", href: "/medical", icon: LayoutDashboard },
      { label: "Medical Screening", href: "/medical/screening", icon: Stethoscope },
      { label: "Screening History", href: "/medical/history", icon: History },
      { label: "Blacklisted NICs", href: "/medical/blacklist", icon: Ban },
    ],
  },
  HSEQ_OFFICER: {
    label: "HSEQ Officer",
    shortLabel: "HSEQ",
    dashboardPath: "/hseq",
    description: "Site induction, photo capture, ID card issuance + electrical inspection.",
    nav: [
      { label: "Dashboard", href: "/hseq", icon: LayoutDashboard },
      { label: "Induction Workstation", href: "/hseq/induction", icon: ClipboardCheck },
      { label: "Inducted Employees", href: "/hseq/inducted-employees", icon: IdCard },
      { label: "Employee QR Codes", href: "/hseq/employee-qr-codes", icon: Download },
      { label: "Electrical Inspection", href: "/hseq/electrical-inspection", icon: Zap },
      { label: "Inspection History", href: "/hseq/inspection-history", icon: History },
    ],
  },
  SECURITY_OFFICER: {
    label: "Security Officer (Gate)",
    shortLabel: "Security",
    dashboardPath: "/security",
    description: "Gate access control, NIC scanning and gate passes.",
    nav: [
      { label: "Scan Workstation", href: "/security", icon: ScanLine },
      { label: "Live Dashboard", href: "/security/dashboard", icon: LayoutDashboard },
      { label: "Permanent Movements", href: "/permanent-movements", icon: ArrowLeftRight },
    ],
  },
  INTERNAL_SECURITY: {
    label: "Internal Security",
    shortLabel: "Internal Sec.",
    dashboardPath: "/internal-security",
    description: "Process tool gate passes — IN/OUT movements with full audit trail.",
    nav: [
      { label: "Dashboard", href: "/internal-security", icon: LayoutDashboard },
      { label: "Gate Pass Processing", href: "/internal-security/gate-pass", icon: FileText },
      { label: "Movement History", href: "/internal-security/movements", icon: History },
      { label: "Contractor Inventory", href: "/internal-security/contractor-inventory", icon: Boxes },
    ],
  },
  CONTRACTOR: {
    label: "Contractor",
    shortLabel: "Contractor",
    dashboardPath: "/contractor",
    description: "Submit workforce, manage gate passes, view clearances.",
    nav: [
      { label: "Dashboard", href: "/contractor", icon: LayoutDashboard },
      { label: "My Employees", href: "/contractor/employees", icon: Users },
      { label: "My Vehicles", href: "/contractor/vehicles", icon: Truck },
      { label: "My Equipment", href: "/contractor/equipment", icon: Wrench },
      { label: "My Requests", href: "/contractor/requests", icon: Inbox },
      { label: "Movement History", href: "/contractor/movement-history", icon: Activity },
      { label: "Tool Movements", href: "/contractor/tool-movements", icon: ArrowLeftRight },
      { label: "Reports", href: "/contractor/reports", icon: Download },
    ],
  },
};

export function getRoleConfig(role: Role): RoleConfig {
  return roleConfig[role];
}
